export default {
  notesDisplayed: [],
  notesDisplayedOther: [],
  notesDisplayedString: "",
  correctNote: "placeholder",
  pianoClickedKey: "",
  indexd: 0,
  opacity: 0,
  rightorWrong: "placeholder",
  isSharp: false,
  isFlat: false,
  isTreble: false,
  afterNote: "2",
  lastSpacing: 0,
  noteAmount: 12,
};
